
---
title: "NBA - Radio Button"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    logo: logo.png
    source_code: embed
    social: menu

runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library(flexdashboard)
library(tidyverse)
library(plotly)
library(knitr)
library(DT)
df <- read_csv('nba_data_processed.csv')
df <- drop_na(df, Age)
df <- drop_na(df, Pos)
df <- df %>% filter(Tm =='BOS' | Tm =='NYK' | Tm =='BRK' | Tm =='PHI' | Tm =='TOR')
df$Survived = factor(df$Pos)
df$Pclass = factor(df$PTS)


nba_pos <- unique(df$Pos)
```

{.sidebar}
=======================================================================

The NBA player statistics data set provides detailed performance metrics for various NBA players from the 2022-2023 season. This data is filtered into the teams in the Northeast. Select the position to see how the position differs.


```{r}
radioButtons(inputId = "Tm_input", 
             label = h2("Select Team"),
             choices = c('BOS','NYK','BRK','PHI','TOR'),
             inline = TRUE,
             selected = 'BOS')
```

Main Tab 1
=======================================================================

Column {data-width=500}
-----------------------------------------------------------------------

### Density Plot

```{r}
renderPlotly({
  p1 <- df %>% 
    filter(Tm==input$Tm_input) %>% 
    ggplot(aes(x=Age, color=Pos))+
    geom_density()
  ggplotly(p1)
})
```

Column {data-width=500}
-----------------------------------------------------------------------

### Bar Plot

```{r}
renderPlotly({
  p2 <- df %>% 
    filter(Tm==input$Tm_input) %>% 
    ggplot(aes(x=Tm, fill=Pos))+
    geom_bar()
  ggplotly(p2)
})
```
