
---
title: "NBA - Check Box"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    logo: logo.png
    source_code: embed
    social: menu

runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library(flexdashboard)
library(tidyverse)
library(plotly)
library(knitr)
library(DT)
df <- read_csv('nba_data_processed.csv')
df <- drop_na(df, Age)
df <- drop_na(df, Pos)
df <- df %>% filter(Tm =='BOS' | Tm =='NYK' | Tm =='BRK' | Tm =='PHI' | Tm =='TOR', Player == 'Jaylen Brown' | Player =='Marcus Smart' | Player == 'Jayson Tatum' | Player == 'Derrick White' | Player == 'Al Horford' | Player == 'Jalen Brunson' | Player == 'Quentin Grimes' | Player == 'RJ Barrett' | Player == 'Julius Randle' | Player == 'Mitchell Robinson' | Player == 'Tyrese Maxey' | Player == 'James Harden' | Player == 'P.J. Tucker' | Player =='Tobias Harris' | Player =='Joel Embiid' | Player == 'Fred VanVleet' | Player == 'Scottie Barnes' | Player =='OG Anunoby' | Player =='Pascal Siakam' | Player == 'Jakob Poeltl' | Player =='Spencer Dinwiddie' | Player == 'Mikal Bridges' | Player == 'Dorian Finney-Smith' | Player == 'Cameron Johnson' | Player == 'Nic Claxton') 

df$Tm = factor(df$Tm)
df$Player = factor(df$Player)


nba_pos <- unique(df$Pos)
```

{.sidebar}
=======================================================================

The NBA player statistics data set provides detailed performance metrics for various NBA players from the 2022-2023 season. This data is filtered into the teams in the Northeast, and their starting players. Select the input to create the plot.

```{r}
checkboxGroupInput(inputId = "pos_input", 
                   label = h3("Position"),
                   choices = unique(df$Pos), 
                   inline = TRUE,
                   selected = 'C')

```

Main Tab 1
=======================================================================

Column {data-width=500}
-----------------------------------------------------------------------

### Density Plot

```{r}
renderPlotly({
  p1 <- df %>% 
    filter(Pos %in% input$pos_input) %>% 
    ggplot(aes(x=Age, y=Tm, color=Player))+
    geom_point()
  ggplotly(p1)
})
```

Column {data-width=500}
-----------------------------------------------------------------------

### Bar Plot

```{r}
renderPlotly({
  p2 <- df %>% 
    filter(Pos %in% input$pos_input) %>% 
    ggplot(aes(x=Tm, fill=Player))+
    geom_bar()
  ggplotly(p2)
})
```
